//! Error types for fallible conversions.

use thiserror::Error;

/// Error type for `TryFrom` conversions generated by `relate_structs!`.
///
/// This is the default error type when using `~>?` syntax without specifying
/// a custom error type. It automatically captures common conversion errors.
///
/// # Example
///
/// ```rust,ignore
/// use relate::{relate_structs, ConversionError};
///
/// relate_structs! {
///     Source ~>? Target {
///         value => .parse()?,  // ParseIntError auto-converts
///     }
/// }
///
/// let result: Result<Target, ConversionError> = source.try_into();
/// match result {
///     Ok(target) => println!("Success: {:?}", target),
///     Err(ConversionError::ParseInt(e)) => println!("Parse error: {}", e),
///     Err(e) => println!("Other error: {}", e),
/// }
/// ```
#[derive(Debug, Error)]
pub enum ConversionError {
    /// A required field was None when a value was expected.
    #[error("missing required field: {0}")]
    MissingField(&'static str),

    /// Integer parsing failed.
    #[error("failed to parse integer: {0}")]
    ParseInt(#[from] std::num::ParseIntError),

    /// Float parsing failed.
    #[error("failed to parse float: {0}")]
    ParseFloat(#[from] std::num::ParseFloatError),

    /// Boolean parsing failed.
    #[error("failed to parse boolean: {0}")]
    ParseBool(#[from] std::str::ParseBoolError),

    /// UTF-8 conversion failed.
    #[error("invalid UTF-8: {0}")]
    Utf8(#[from] std::str::Utf8Error),

    /// UTF-8 string conversion failed.
    #[error("invalid UTF-8 string: {0}")]
    FromUtf8(#[from] std::string::FromUtf8Error),

    /// Custom error message.
    #[error("{0}")]
    Custom(String),
}

impl ConversionError {
    /// Create a custom error with a message.
    #[must_use]
    pub fn custom(msg: impl Into<String>) -> Self { Self::Custom(msg.into()) }

    /// Create a missing field error.
    #[must_use]
    pub const fn missing_field(field: &'static str) -> Self { Self::MissingField(field) }
}

impl From<String> for ConversionError {
    fn from(s: String) -> Self { Self::Custom(s) }
}

impl From<&str> for ConversionError {
    fn from(s: &str) -> Self { Self::Custom(s.to_string()) }
}
